// WordSearch.idl
import "WordItem.idl";
import "DictionaryItemInWordDetail.idl";


namespace WordWiz
{
    [default_interface]
    runtimeclass WordSearch
    {
        WordSearch();
        Windows.Foundation.Collections.IVector<WordWiz.WordItem> Search(String query);

        Windows.Foundation.Collections.IVector<WordWiz.DictionaryItemInWordDetail> GetAvailableDictionaries(String word);
        String GetDictionaryHtmlContent(String word, String dictionaryName);
    
    }
}