// WordSearchResultItem.idl
namespace WordWiz
{
    [default_interface]
    runtimeclass WordSearchResultItem : Microsoft.UI.Xaml.Controls.UserControl
    {
        WordSearchResultItem();

    // Dependency Properties to display word and explanation
    String WordDisplay;
    String ExplanationDisplay;
    // Event for item click, if needed
    // event Microsoft.UI.Xaml.RoutedEventHandler ItemClicked;
}
}