// WordSearchResultList.idl
import "WordItem.idl"; // Import WordItem definition

namespace WordWiz
{
    [default_interface]
    runtimeclass WordSearchResultList : Microsoft.UI.Xaml.Controls.UserControl
    {
        WordSearchResultList();
        Windows.Foundation.Collections.IObservableVector<WordWiz.WordItem> Items { get; };
    }
}