import "WordItem.idl";

namespace WordWiz
{
    [default_interface]
    runtimeclass WordSearchResultPage : Microsoft.UI.Xaml.Controls.Page
    {
        WordSearchResultPage(); // 构造函数
        WordWiz.WordItem PageLevelSelectedItem; // 页面级选中项属性
        static Microsoft.UI.Xaml.DependencyProperty PageLevelSelectedItemProperty{ get; };
        
        // Items 属性用于绑定到 ListView
        Windows.Foundation.Collections.IObservableVector<WordWiz.WordItem> Items{ get; };
    }
}