// WordDetails.idl
import "WordItem.idl";

namespace WordWiz
{
    [default_interface]
    runtimeclass WordDetails : Microsoft.UI.Xaml.Controls.UserControl
    {
        WordDetails();

    // 依赖属性，用于接收要显示的 WordItem
    WordWiz.WordItem ItemToDisplay;
    static Microsoft.UI.Xaml.DependencyProperty ItemToDisplayProperty{ get; };
    String GetFavoriteIconGlyph(String item);
    }
}